<a href="https://colab.research.google.com/github/VineeshaKuravi/numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
from time import process_time

In [ ]:
python=[i for i in range(100000)]
start=process_time()
res=[i+5 for i in python]
end=process_time()
print(end-start)

0.012586401999999275


In [ ]:
np_array=np.array([i for i in range(100000)])
start=process_time()
np_array+=5
end=process_time()
print(end-start)

0.0011862220000011803


In [ ]:
np_array=np.array([])
type(np_array)

numpy.ndarray

In [ ]:
np_array=np.array([(1,2,3,4),(5,6,7,8)])
print(np_array)
np_array.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
np_array=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(np_array)
np_array.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

In [ ]:
np_array=np.array([(1,2,3,4)])
np_array.shape

(1, 4)

Initial placeholders  in numpy arrays


In [ ]:
x=np.zeros((4,5))
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
y=np.ones((5,5),dtype=int)
print(y)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
z=np.full((5,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


Identity Matrix


In [ ]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Random values


In [ ]:
a=np.random.random((4,5))
print(a)

[[0.60463821 0.51321902 0.16749767 0.5075498  0.0472013 ]
 [0.51729611 0.36438402 0.64231876 0.58252215 0.3682263 ]
 [0.14992221 0.57116873 0.77482798 0.20675223 0.03394049]
 [0.07795018 0.72713376 0.71230376 0.77954159 0.2167775 ]]


Random integer values within range

In [ ]:
a=np.random.randint(10,100,(2,3))
print(a)

[[11 41 80]
 [77 63 38]]


Evenly spaced values and no. of values

In [ ]:
a=np.linspace(10,20,5,dtype=int)
print(a)

[10 12 15 17 20]


Evenly spaced values and step

In [ ]:
a=np.arange(10,20,5)
print(a)

[10 15]


Convert list to array( we use np.asarray to convert any datatype to nump array)

In [ ]:
a=[1,2,3,4]
np_array=np.asarray(a)
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

Analysing numpy array


In [ ]:
a=np.array([(1,2,3),[1,2,3]])
print(a)

[[1 2 3]
 [1 2 3]]


In [ ]:
print(a.shape)

(2, 3)


In [ ]:
print(a.ndim)

2


In [ ]:
print(a.size)

6


In [ ]:
print(a.dtype)

int64


In [ ]:
Mathematical Calculations on np array

In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[0 1 1]
 [7 5 7]
 [1 9 4]]
[[10 19 12]
 [19 18 14]
 [14 15 13]]
[[10 20 13]
 [26 23 21]
 [15 24 17]]
[[-10 -18 -11]
 [-12 -13  -7]
 [-13  -6  -9]]
[[  0  19  12]
 [133  90  98]
 [ 14 135  52]]
[[0.         0.05263158 0.08333333]
 [0.36842105 0.27777778 0.5       ]
 [0.07142857 0.6        0.30769231]]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 6 4]
 [9 8 8]
 [1 5 3]]
[[15 13 15]
 [11 11 18]
 [12 13 13]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[18 19 19]
 [20 19 26]
 [13 18 16]]
[[-12  -7 -11]
 [ -2  -3 -10]
 [-11  -8 -10]]
[[ 45  78  60]
 [ 99  88 144]
 [ 12  65  39]]
[[0.2        0.46153846 0.26666667]
 [0.81818182 0.72727273 0.44444444]
 [0.08333333 0.38461538 0.23076923]]


Manipulations on Array

In [ ]:
a=np.random.randint(10,20,(3,4))
print(a)
print(a.shape)

[[16 14 16 15]
 [15 16 13 15]
 [19 19 19 12]]
(3, 4)


In [ ]:
t=np.transpose(a)
print(t)
print(t.shape)

[[16 15 19]
 [14 16 19]
 [16 13 19]
 [15 15 12]]
(4, 3)


In [ ]:
a=np.random.randint(10,20,(3,4))
print(a)
print(a.shape)

[[10 13 17 19]
 [14 17 15 18]
 [12 19 18 19]]
(3, 4)


In [ ]:
t2=a.T
print(t2)
print(t2.shape)

[[10 14 12]
 [13 17 19]
 [17 15 18]
 [19 18 19]]
(4, 3)


Reshaping an array


In [ ]:
a=np.random.randint(10,20,(3,4))
print(a)
print(a.shape)

[[15 15 10 18]
 [10 12 12 14]
 [19 10 14 18]]
(3, 4)


In [ ]:
b=a.reshape(4,3)
print(b)
print(b.shape)

[[15 15 10]
 [18 10 12]
 [12 14 19]
 [10 14 18]]
(4, 3)
